print("Tugas Bahasa Pemrograman")
print("========================")
print()
nama = input("Masukan Nama Lengkap   : ")
np = input("Masukan Nama Panggilan : ")
nim = input("Masukan NIM            : ")
lahir = input("Masukan Tempat Lahir   : ")
umur = input("Masukan Umur Anda      : ")
alamat = input("Masukan Alamat         : ")
tlpn = input("Masukan Nomor Telepon  : ")

print()
print("Assalamua'laikum")
print()
print("Let me introduce my self. my name is",nama,"but you can call me",np,"My NIM is",nim,"I was born in",lahir,"and I am",umur,"years old. I am very gald if you want to invite my house in",alamat,". So, don't forget to call me before with the number",tlpn,)
print()
print("Thank You.")